### ISSUE TITLE
Version bump for Serde?

### ISSUE THREAD

**Issue by alanhdu** [iron/urlencoded#68] opened 2017-03-10 21:56 UTC
`urlencoded` depends on `bodyparser 0.5`, which depends on `serde 0.8`.  Would it be possible to cut a new release that uses `bodyparser 0.6` instead (which would let us use `serde 0.9` without weird type mismatches)?

**Comment by euclio** [comment] 2017-04-25 13:46
`bodyparser` has been bumped again in #70 to pull in serde 1.0. @untitaker, are you in charge of releases?

**Comment by Hoverbear** [comment] 2017-06-22 05:56
@euclio Unfortunately I can't release this. Maybe @SkylerLipthay or @reem could.

**Comment by durka** [comment] 2017-08-08 21:32
Is this package maintained? We could release it under a new name...

**Comment by Hoverbear** [comment] 2017-08-09 07:20
@durka Yes. Myself, @reem, @untitaker, and @SkylerLipthay . However there are still some permissions issues around who can publish what on crates.io.

**Comment by durka** [comment] 2017-08-09 15:45
@Hoverbear I apologize for the flippant tone, which was unwarranted. I was just trying to make some noise since it seems like none of those with said permissions have been paying attention. It looks like @michaelsproul and @theptrk are the other two people with crates.io rights?

**Comment by Hoverbear** [comment] 2017-08-09 17:59
Hopefully one of them can help. :)

**Comment by untitaker** [comment] 2017-08-09 18:23
I suppose 0.6.0 is the next version? Or do we not expose this dependency?

**Comment by durka** [comment] 2017-08-09 18:41
It's 0.7 now (for serde 1.0). Maybe a serde 0.9 version of urlencoded should be released as well though, in case anyone still needs it to harmonize their dependencies.

**Comment by michaelsproul** [comment] 2017-08-09 22:20
Hi all, I'd love to help, and although it seems I'm listed in Cargo.toml's `authors` field for my meagre contributions, I'm *not* a crate owner on crates.io and can't publish. However, it looks like everyone in the `iron-dev` team can publish: https://github.com/orgs/iron/teams/dev-team/members, which includes a bunch of people here :)

Cargo docs on publishing for reference: http://doc.crates.io/crates-io.html

Good luck!

**Comment by Manishearth** [comment] 2017-08-11 22:20
Oh, we had this issue recently too in Servo. Does this org have crates.io as an approved OAuth app?

Because if it doesn't then crates.io will silently ignore the dev-team stuff.

What I suggest is you go to your settings and revoke permission from crates.io. Then log in to the site again -- at that point you see which orgs have approved it, and are given the ability to approve it for orgs you manage, or request approval for orgs which you are a part of but don't manage. If you're in the last bucket you can ask the Iron org owners to approve it from settings after you put in the request.

**Comment by untitaker** [comment] 2017-08-12 13:52
@Manishearth it was always approved before, I re-authed as you instructed and nothing happens. I don't understand why @Hoverbear doesn't have access to publish a new version.

the iron doesn't have any application restrictions at all, so apps wouldn't need explicit approval.

@Hoverbear please try if any of the advice by @michaelsproul and @Manishearth helps, otherwise I'll just push a new version.

**Comment by robinst** [comment] 2017-09-26 01:11
@untitaker: To try to move this along, can you add some others explicitly as owners for this crate, like this?:

    cargo owner --add Hoverbear
    cargo owner --add michaelsproul

Then they can try to see if they have more luck with adding the whole team as owners. Maybe removing the team and adding it again helps (not sure if the name is `dev-team` or `iron-dev`?):

    cargo owner --remove github:iron:dev-team
    cargo owner --add github:iron:dev-team

**Comment by untitaker** [comment] 2017-10-01 19:24
I added @Hoverbear @michaelsproul @sfackler as owner for this crate, however, when trying your second set of commands I get an error when trying to re-add the team:

```
$ cargo owner --add github:iron:dev-team                   
    Updating registry `https://github.com/rust-lang/crates.io-index`                                                   
       Owner adding ["github:iron:dev-team"] to crate urlencoded                                                       
error: failed to add owners to crate urlencoded: api errors: only members of github:iron:dev-team can add it as an owner
```

**Comment by Manishearth** [comment] 2017-10-01 22:43
An org admin will need to reauth Crates.io.

The way you do this is by removing Crates.io from your approved applications for your personal account, and then trying to log in to the site again, at which point it will ask you to authorize crates.io, and will give you the option to authorize it for organizations you have access to; or to request access from the admins.

There's probably a better way to do it, I just don't know what.

**Comment by untitaker** [comment] 2017-10-02 04:02
Crates.io is already authorized for the org, as i am admin

On 2 October 2017 00:43:55 GMT+02:00, Manish Goregaokar <notifications@github.com> wrote:
>An org admin will need to reauth Crates.io.
>
>The way you do this is by removing Crates.io from your approved
>applications for your personal account, and then trying to log in to
>the site again, at which point it will ask you to authorize crates.io,
>and will give you the option to authorize it for organizations you have
>access to; or to request access from the admins.
>
>There's probably a better way to do it, I just don't know what.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/iron/urlencoded/issues/68#issuecomment-333412412

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Manishearth** [comment] 2017-10-02 04:03
> as i am admin

note that just being an admin and giving personal access to crates will not authorize it for the org as well. these are separate permissions systems.

**Comment by untitaker** [comment] 2017-10-02 07:36
The org doesn't have any additional protections:

![2017-10-02-093534_762x168_scrot](https://user-images.githubusercontent.com/837573/31067811-1e50dec2-a755-11e7-8596-26cb62108d0b.png)

**Comment by robinst** [comment] 2017-10-02 23:17
@untitaker can you add @Manishearth as an admin of the iron organization so he can have a look?

**Comment by untitaker** [comment] 2017-10-03 05:59
done

**Comment by Manishearth** [comment] 2017-10-03 15:24
Hm, I can't either, since I don't have owner access on crates.io. But you're right, it should work. Perhaps try `cargo owner -a iron:dev-team`?

**Comment by untitaker** [comment] 2017-10-03 18:50
That doesn't work either, cargo rejects the format of `iron:dev-team` very
early.

**Comment by robinst** [comment] 2017-10-03 18:59
@untitaker can you add @Manishearth as an owner to the crate?:

    cargo owner --add Manishearth

**Comment by untitaker** [comment] 2017-10-03 19:00
done

**Comment by Manishearth** [comment] 2017-10-03 20:05
Interesting, I get the saem error, but not the same error when I try to add `servo:cargo-publish`

**Comment by Manishearth** [comment] 2017-10-03 20:45
Turns out this is a Cargo bug wrt team ids, it's being fixed.

**Comment by robinst** [comment] 2017-10-04 19:03
@Manishearth: Yay! Do you have a link to an issue/PR?

**Comment by Manishearth** [comment] 2017-10-04 19:05
https://github.com/rust-lang/crates.io/pull/1107

(@carols10cents is amazing)

**Comment by robinst** [comment] 2017-10-18 04:19
Yay! Looks like the fix was merged. @Manishearth, does adding the team work now?

**Comment by remram44** [comment] 2017-10-18 04:26
I'm excited for Iron to make a comeback in the active web frameworks! This release has been delayed over 6 months already, hopefully Cargo is fixed and we won't see this happen again 😅

**Comment by Manishearth** [comment] 2017-10-18 05:23
it worked!

**Comment by robinst** [comment] 2017-10-18 18:30
Yay! So maybe also run the command on all the other iron crates, just to make sure.

Also, who wants to do the releasing now? (I'm willing to help by the way, but someone would need to add me to the list of maintainers.)

**Comment by Manishearth** [comment] 2017-10-18 20:44
(I'm only an owner for this crate, need @untitaker to look at the others)

I tried cargo-publishing this crate, it's already published

**Comment by durka** [comment] 2017-10-18 23:54
@Manishearth the version number needs to be bumped.

**Comment by untitaker** [comment] 2017-10-19 20:18
Whichever crate I try, I get the error message that the GitHub
org is already an owner.

**Comment by untitaker** [comment] 2017-10-19 20:18
Please ping me if a particular repo is missing.

**Comment by robinst** [comment] 2017-10-19 21:06
Cool, so maybe it fixed it for all crates :).

So, who is going to release all the things that need releasing? Seems like that is at least this crate and iron itself.

**Comment by euclio** [comment] 2017-11-02 16:21
iron/params will need to bump this crate and release as well

**Comment by untitaker** [comment] 2017-11-05 12:59
Done!

**Comment by est31** [comment] 2017-11-19 04:28
It would be really cool if a new version could be released that includes #70 because that hasn't happened yet! I don't want to pull in pre 1.0 serde :)

**Comment by Manishearth** [comment] 2017-11-19 04:43
Oh, I thought this was published. My bad.

**Comment by Manishearth** [comment] 2017-11-19 04:43
@untitaker can you bump the version in this repo and republish? I can do it too but not at the moment

**Comment by robinst** [comment] 2017-11-19 07:34
body-parser needs to be released first: https://github.com/iron/body-parser/pull/79

See this issue in iron for all dependencies and the order: https://github.com/iron/iron/issues/551

**Comment by iori-yja** [comment] 2017-11-19 17:19
This refers the iron/body-parser#79 's version. https://github.com/iron/urlencoded/pull/72
The build is failed because the version is not released yet ... But I confirmed on my local test with the modification, if my memory is correct.

**Comment by untitaker** [comment] 2017-11-21 12:13
body-parser is now released.

**Comment by robinst** [comment] 2017-11-23 03:23
urlencoded 0.6.0 has been released, which depends on bodyparser 0.8, which depends on serde 1.0. So I think we can close this now.

**Closed** 2017-11-23 03:34 UTC

**Comment by est31** [comment] 2017-11-23 05:10
Thanks! Now I do need a new release of staticfile however because you also switched to iron 0.6.0...

**Comment by robinst** [comment] 2017-11-23 05:37
@est31: The iron dependency has the constraints `>= 0.5, <0.7`, so in theory it should still work with 0.5.0. Have you tried?

**Comment by est31** [comment] 2017-11-23 05:51
Oh that's interesting... Yep it works. Thank you @robinst !
